### PR TITLE
Added redirect function on AB cloaking

### PR DESCRIPTION
**Pull request by dave9123**
If it works fine, I'll add to server branch as well

### CODE REVIEW

**Comment by FatGrizzly** [comment]
was this tested?

**Comment by dave9123** [comment]
firefox_nYxkYPOL3a
Here's for the default redirect

**Comment by dave9123** [comment]
Made it redirect to Google using the .replace function. Removes it from the history
firefox_nYxkYPOL3a
(found an error, will fix it)

**Comment by dave9123** [comment]
Fixed it, should be working properly now
firefox_JOH7hmfnVo

**Pull request merged**
